#!/usr/bin/env python
import os
# To import anything under django.*, we must set this variable.
os.environ['DJANGO_SETTINGS_MODULE'] = 'planetplanet.settings'
# Import the admin module. The media directory is right under it!
import django.contrib.admin
# Retrieve the absolute path of the admin module.
admindir = os.path.dirname(django.contrib.admin.__file__)
admin_mediadir = os.path.join(admindir, 'media')
staticlink = os.path.join('static', 'admin_media')
if os.path.islink(staticlink):
    os.unlink(staticlink)
os.symlink(admin_mediadir, staticlink)

# planet app static files
staticlink = os.path.join('static', 'planet')
if os.path.islink(staticlink):
    os.unlink(staticlink)
os.symlink('/home/dotcloud/current/planetplanet/static/planet', staticlink)
